
services:
  - type: web
    name: web4api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: ALLOW_ORIGIN
        value: https://web4application.github.io
      - key: SENTRY_DSN
        value: <https://55038c1e414932ec8d81c34e5ef120fa@o4509364065402880.ingest.de.sentry.io/4509364112457808>
